// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_DiscreteDists_RCPPEXPORTS_H_GEN_
#define RCPP_DiscreteDists_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace DiscreteDists {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("DiscreteDists", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("DiscreteDists", "_DiscreteDists_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in DiscreteDists");
            }
        }
    }

    inline NumericVector cpp_dDMOLBE(const NumericVector& x, const NumericVector& mu, const NumericVector& sigma, const bool& log_prob = false) {
        typedef SEXP(*Ptr_cpp_dDMOLBE)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_cpp_dDMOLBE p_cpp_dDMOLBE = NULL;
        if (p_cpp_dDMOLBE == NULL) {
            validateSignature("NumericVector(*cpp_dDMOLBE)(const NumericVector&,const NumericVector&,const NumericVector&,const bool&)");
            p_cpp_dDMOLBE = (Ptr_cpp_dDMOLBE)R_GetCCallable("DiscreteDists", "_DiscreteDists_cpp_dDMOLBE");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_cpp_dDMOLBE(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(mu)), Shield<SEXP>(Rcpp::wrap(sigma)), Shield<SEXP>(Rcpp::wrap(log_prob)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_DiscreteDists_RCPPEXPORTS_H_GEN_
