// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/DiscreteDists.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// z_cpp
double z_cpp(double lambda, double nu, int max_terms, double tol);
RcppExport SEXP _DiscreteDists_z_cpp(SEXP lambdaSEXP, SEXP nuSEXP, SEXP max_termsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type max_terms(max_termsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(z_cpp(lambda, nu, max_terms, tol));
    return rcpp_result_gen;
END_RCPP
}
// z_vec_cpp
NumericVector z_vec_cpp(NumericVector mu, NumericVector sigma);
RcppExport SEXP _DiscreteDists_z_vec_cpp(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(z_vec_cpp(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// d1_dldm_compo_cpp
double d1_dldm_compo_cpp(double lambda, double nu, int max_terms, double tol);
RcppExport SEXP _DiscreteDists_d1_dldm_compo_cpp(SEXP lambdaSEXP, SEXP nuSEXP, SEXP max_termsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type max_terms(max_termsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(d1_dldm_compo_cpp(lambda, nu, max_terms, tol));
    return rcpp_result_gen;
END_RCPP
}
// d1_vec_dldm_compo_cpp
NumericVector d1_vec_dldm_compo_cpp(NumericVector mu, NumericVector sigma);
RcppExport SEXP _DiscreteDists_d1_vec_dldm_compo_cpp(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(d1_vec_dldm_compo_cpp(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// d2_dldd_compo_cpp
double d2_dldd_compo_cpp(double lambda, double nu, int max_terms, double tol);
RcppExport SEXP _DiscreteDists_d2_dldd_compo_cpp(SEXP lambdaSEXP, SEXP nuSEXP, SEXP max_termsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type max_terms(max_termsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(d2_dldd_compo_cpp(lambda, nu, max_terms, tol));
    return rcpp_result_gen;
END_RCPP
}
// d2_vec_dldd_compo_cpp
NumericVector d2_vec_dldd_compo_cpp(NumericVector mu, NumericVector sigma);
RcppExport SEXP _DiscreteDists_d2_vec_dldd_compo_cpp(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(d2_vec_dldd_compo_cpp(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// dCOMPO_single
double dCOMPO_single(double x, double mu, double sigma, bool log);
RcppExport SEXP _DiscreteDists_dCOMPO_single(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dCOMPO_single(x, mu, sigma, log));
    return rcpp_result_gen;
END_RCPP
}
// dCOMPO_vec
NumericVector dCOMPO_vec(NumericVector x, NumericVector mu, NumericVector sigma, LogicalVector log);
RcppExport SEXP _DiscreteDists_dCOMPO_vec(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dCOMPO_vec(x, mu, sigma, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dDMOLBE
NumericVector cpp_dDMOLBE(const NumericVector& x, const NumericVector& mu, const NumericVector& sigma, const bool& log_prob);
static SEXP _DiscreteDists_cpp_dDMOLBE_try(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dDMOLBE(x, mu, sigma, log_prob));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _DiscreteDists_cpp_dDMOLBE(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP log_probSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_DiscreteDists_cpp_dDMOLBE_try(xSEXP, muSEXP, sigmaSEXP, log_probSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// f11_cpp
double f11_cpp(double gamma, double lambda, int maxiter_series, double tol);
RcppExport SEXP _DiscreteDists_f11_cpp(SEXP gammaSEXP, SEXP lambdaSEXP, SEXP maxiter_seriesSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter_series(maxiter_seriesSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(f11_cpp(gamma, lambda, maxiter_series, tol));
    return rcpp_result_gen;
END_RCPP
}
// dHYPERPO_single
double dHYPERPO_single(double x, double mu, double sigma, bool log);
RcppExport SEXP _DiscreteDists_dHYPERPO_single(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dHYPERPO_single(x, mu, sigma, log));
    return rcpp_result_gen;
END_RCPP
}
// dHYPERPO_vec
NumericVector dHYPERPO_vec(NumericVector x, NumericVector mu, NumericVector sigma, LogicalVector log);
RcppExport SEXP _DiscreteDists_dHYPERPO_vec(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dHYPERPO_vec(x, mu, sigma, log));
    return rcpp_result_gen;
END_RCPP
}
// fun_exp_6_single_cpp
double fun_exp_6_single_cpp(double x, double media, double gamma);
RcppExport SEXP _DiscreteDists_fun_exp_6_single_cpp(SEXP xSEXP, SEXP mediaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type media(mediaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_exp_6_single_cpp(x, media, gamma));
    return rcpp_result_gen;
END_RCPP
}
// fun_exp_6_vec_cpp
NumericVector fun_exp_6_vec_cpp(NumericVector x, NumericVector media, NumericVector gamma);
RcppExport SEXP _DiscreteDists_fun_exp_6_vec_cpp(SEXP xSEXP, SEXP mediaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type media(mediaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_exp_6_vec_cpp(x, media, gamma));
    return rcpp_result_gen;
END_RCPP
}
// obtaining_lambda_single_cpp
double obtaining_lambda_single_cpp(double media, double gamma, double tol, int max_iter);
RcppExport SEXP _DiscreteDists_obtaining_lambda_single_cpp(SEXP mediaSEXP, SEXP gammaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type media(mediaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(obtaining_lambda_single_cpp(media, gamma, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// obtaining_lambda_vec_cpp
NumericVector obtaining_lambda_vec_cpp(NumericVector media, NumericVector gamma);
RcppExport SEXP _DiscreteDists_obtaining_lambda_vec_cpp(SEXP mediaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type media(mediaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(obtaining_lambda_vec_cpp(media, gamma));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _DiscreteDists_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericVector(*cpp_dDMOLBE)(const NumericVector&,const NumericVector&,const NumericVector&,const bool&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _DiscreteDists_RcppExport_registerCCallable() { 
    R_RegisterCCallable("DiscreteDists", "_DiscreteDists_cpp_dDMOLBE", (DL_FUNC)_DiscreteDists_cpp_dDMOLBE_try);
    R_RegisterCCallable("DiscreteDists", "_DiscreteDists_RcppExport_validate", (DL_FUNC)_DiscreteDists_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_DiscreteDists_z_cpp", (DL_FUNC) &_DiscreteDists_z_cpp, 4},
    {"_DiscreteDists_z_vec_cpp", (DL_FUNC) &_DiscreteDists_z_vec_cpp, 2},
    {"_DiscreteDists_d1_dldm_compo_cpp", (DL_FUNC) &_DiscreteDists_d1_dldm_compo_cpp, 4},
    {"_DiscreteDists_d1_vec_dldm_compo_cpp", (DL_FUNC) &_DiscreteDists_d1_vec_dldm_compo_cpp, 2},
    {"_DiscreteDists_d2_dldd_compo_cpp", (DL_FUNC) &_DiscreteDists_d2_dldd_compo_cpp, 4},
    {"_DiscreteDists_d2_vec_dldd_compo_cpp", (DL_FUNC) &_DiscreteDists_d2_vec_dldd_compo_cpp, 2},
    {"_DiscreteDists_dCOMPO_single", (DL_FUNC) &_DiscreteDists_dCOMPO_single, 4},
    {"_DiscreteDists_dCOMPO_vec", (DL_FUNC) &_DiscreteDists_dCOMPO_vec, 4},
    {"_DiscreteDists_cpp_dDMOLBE", (DL_FUNC) &_DiscreteDists_cpp_dDMOLBE, 4},
    {"_DiscreteDists_f11_cpp", (DL_FUNC) &_DiscreteDists_f11_cpp, 4},
    {"_DiscreteDists_dHYPERPO_single", (DL_FUNC) &_DiscreteDists_dHYPERPO_single, 4},
    {"_DiscreteDists_dHYPERPO_vec", (DL_FUNC) &_DiscreteDists_dHYPERPO_vec, 4},
    {"_DiscreteDists_fun_exp_6_single_cpp", (DL_FUNC) &_DiscreteDists_fun_exp_6_single_cpp, 3},
    {"_DiscreteDists_fun_exp_6_vec_cpp", (DL_FUNC) &_DiscreteDists_fun_exp_6_vec_cpp, 3},
    {"_DiscreteDists_obtaining_lambda_single_cpp", (DL_FUNC) &_DiscreteDists_obtaining_lambda_single_cpp, 4},
    {"_DiscreteDists_obtaining_lambda_vec_cpp", (DL_FUNC) &_DiscreteDists_obtaining_lambda_vec_cpp, 2},
    {"_DiscreteDists_RcppExport_registerCCallable", (DL_FUNC) &_DiscreteDists_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_DiscreteDists(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
