# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

z_cpp <- function(lambda, nu, max_terms = 1000L, tol = 1e-10) {
    .Call('_DiscreteDists_z_cpp', PACKAGE = 'DiscreteDists', lambda, nu, max_terms, tol)
}

z_vec_cpp <- function(mu, sigma) {
    .Call('_DiscreteDists_z_vec_cpp', PACKAGE = 'DiscreteDists', mu, sigma)
}

d1_dldm_compo_cpp <- function(lambda, nu, max_terms = 1000L, tol = 1e-10) {
    .Call('_DiscreteDists_d1_dldm_compo_cpp', PACKAGE = 'DiscreteDists', lambda, nu, max_terms, tol)
}

d1_vec_dldm_compo_cpp <- function(mu, sigma) {
    .Call('_DiscreteDists_d1_vec_dldm_compo_cpp', PACKAGE = 'DiscreteDists', mu, sigma)
}

d2_dldd_compo_cpp <- function(lambda, nu, max_terms = 1000L, tol = 1e-10) {
    .Call('_DiscreteDists_d2_dldd_compo_cpp', PACKAGE = 'DiscreteDists', lambda, nu, max_terms, tol)
}

d2_vec_dldd_compo_cpp <- function(mu, sigma) {
    .Call('_DiscreteDists_d2_vec_dldd_compo_cpp', PACKAGE = 'DiscreteDists', mu, sigma)
}

dCOMPO_single <- function(x, mu = 1, sigma = 1, log = FALSE) {
    .Call('_DiscreteDists_dCOMPO_single', PACKAGE = 'DiscreteDists', x, mu, sigma, log)
}

dCOMPO_vec <- function(x, mu, sigma, log) {
    .Call('_DiscreteDists_dCOMPO_vec', PACKAGE = 'DiscreteDists', x, mu, sigma, log)
}

cpp_dDMOLBE <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('_DiscreteDists_cpp_dDMOLBE', PACKAGE = 'DiscreteDists', x, mu, sigma, log_prob)
}

f11_cpp <- function(gamma, lambda, maxiter_series = 10000L, tol = 1.0e-10) {
    .Call('_DiscreteDists_f11_cpp', PACKAGE = 'DiscreteDists', gamma, lambda, maxiter_series, tol)
}

dHYPERPO_single <- function(x, mu = 1, sigma = 1, log = FALSE) {
    .Call('_DiscreteDists_dHYPERPO_single', PACKAGE = 'DiscreteDists', x, mu, sigma, log)
}

dHYPERPO_vec <- function(x, mu, sigma, log) {
    .Call('_DiscreteDists_dHYPERPO_vec', PACKAGE = 'DiscreteDists', x, mu, sigma, log)
}

fun_exp_6_single_cpp <- function(x, media, gamma) {
    .Call('_DiscreteDists_fun_exp_6_single_cpp', PACKAGE = 'DiscreteDists', x, media, gamma)
}

fun_exp_6_vec_cpp <- function(x, media, gamma) {
    .Call('_DiscreteDists_fun_exp_6_vec_cpp', PACKAGE = 'DiscreteDists', x, media, gamma)
}

obtaining_lambda_single_cpp <- function(media, gamma, tol = 1e-10, max_iter = 1000L) {
    .Call('_DiscreteDists_obtaining_lambda_single_cpp', PACKAGE = 'DiscreteDists', media, gamma, tol, max_iter)
}

obtaining_lambda_vec_cpp <- function(media, gamma) {
    .Call('_DiscreteDists_obtaining_lambda_vec_cpp', PACKAGE = 'DiscreteDists', media, gamma)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_DiscreteDists_RcppExport_registerCCallable', PACKAGE = 'DiscreteDists')
})
